__title__ = 'MockAPI'
__description__ = 'A mock API for Web Apps'
__url__ = 'https://github.com/amraneze/MockApi'
__version_info__ = ('0', '0', '1')
__version__ = '.'.join(__version_info__)
__author__ = 'Ait Zeouay Amrane'
__author_email__ = 'a.zeouayamran@gmail.com'
__maintainer__ = 'Ait Zeouay Amrane'
__license__ = 'MIT'
__copyright__ = '(c) 2020 by Ait Zeouay Amrane'